spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/city_management
    password: postgres
    username: postgres
  application:
    name: CityManagement
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    enabled: false
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: TRACE

eureka:
  client:
    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true